[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
